# Adjustment


start_time="2021-01-01"

end_time="2021-12-31"

Daily Arithmetic Mean may change 

In [2]:
import pandas as pd
import numpy as np

In [4]:
df_p = pd.read_csv('c/part-00000-f6d12335-bd1c-4f64-8e51-7c3d1ec94ae7-c000.csv')

In [5]:
df_p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1241290 entries, 0 to 1241289
Data columns (total 31 columns):
 #   Column               Non-Null Count    Dtype  
---  ------               --------------    -----  
 0   Latitude             1241290 non-null  float64
 1   Longitude            1241290 non-null  float64
 2   POC                  1241290 non-null  int64  
 3   Event Type           1241290 non-null  object 
 4   count                1241290 non-null  int64  
 5   State Code           1241290 non-null  int64  
 6   County Code          1241290 non-null  int64  
 7   Site Num             1241290 non-null  int64  
 8   Parameter Code       1241290 non-null  int64  
 9   Datum                1241290 non-null  object 
 10  Parameter Name       1241290 non-null  object 
 11  Sample Duration      1241290 non-null  object 
 12  Pollutant Standard   1241290 non-null  object 
 13  Date Local           1241290 non-null  object 
 14  Units of Measure     1241290 non-null  object 
 15

In [14]:
Coordinates_p = pd.read_csv('cord.csv')

In [7]:
num = len(Coordinates)
num

276

In [8]:
pd.set_option('display.max_columns',None)
df_p.head(5)

Latitude  Longitude  POC Event Type  count  State Code  County Code  \
0  43.46611  -88.62111    1       None   5072          55           27   
1  43.46611  -88.62111    1       None   5072          55           27   
2  43.46611  -88.62111    1       None   5072          55           27   
3  43.46611  -88.62111    1       None   5072          55           27   
4  43.46611  -88.62111    1       None   5072          55           27   

   Site Num  Parameter Code  Datum   Parameter Name Sample Duration  \
0         1           42101  WGS84  Carbon monoxide          1 HOUR   
1         1           42101  WGS84  Carbon monoxide          1 HOUR   
2         1           42101  WGS84  Carbon monoxide          1 HOUR   
3         1           42101  WGS84  Carbon monoxide          1 HOUR   
4         1           42101  WGS84  Carbon monoxide          1 HOUR   

  Pollutant Standard                     Date Local   Units of Measure  \
0     CO 1-hour 1971  2015-01-01T00:00:00.000-05:00  Parts per million   
1     CO 1-hour 1971  2021-01-01T00:00:00.000-05:00  Parts per million   
2     CO 1-hour 1971  2015-01-02T00:00:00.000-05:00  Parts per million   
3     CO 1-hour 1971  2021-01-02T00:00:00.000-05:00  Parts per million   
4     CO 1-hour 1971  2015-01-03T00:00:00.000-05:00  Parts per million   

   Observation Count  Observation Percent  Arithmetic Mean  1st Max Value  \
0                 23                 96.0         0.189739          0.213   
1                 23                 96.0         0.235087          0.262   
2                 23                 96.0         0.216130          0.343   
3                 23                 96.0         0.204130          0.232   
4                 23                 96.0         0.337783          0.377   

   1st Max Hour  AQI  Method Code  \
0             0  NaN        593.0   
1            18  NaN        593.0   
2            23  NaN        593.0   
3            21  NaN        593.0   
4             9  NaN        593.0   

                                         Method Name        Local Site Name  \
0  INSTRUMENTAL - Gas Filter Correlation Teledyne...  HORICON WILDLIFE AREA   
1  INSTRUMENTAL - Gas Filter Correlation Teledyne...  HORICON WILDLIFE AREA   
2  INSTRUMENTAL - Gas Filter Correlation Teledyne...  HORICON WILDLIFE AREA   
3  INSTRUMENTAL - Gas Filter Correlation Teledyne...  HORICON WILDLIFE AREA   
4  INSTRUMENTAL - Gas Filter Correlation Teledyne...  HORICON WILDLIFE AREA   

                                      Address State Name County Name  \
0  Horicon Wildlife Area, 1210 N Palmatory St  Wisconsin       Dodge   
1  Horicon Wildlife Area, 1210 N Palmatory St  Wisconsin       Dodge   
2  Horicon Wildlife Area, 1210 N Palmatory St  Wisconsin       Dodge   
3  Horicon Wildlife Area, 1210 N Palmatory St  Wisconsin       Dodge   
4  Horicon Wildlife Area, 1210 N Palmatory St  Wisconsin       Dodge   

  City Name       CBSA Name            Date of Last Change  point_num  
0  Kekoskee  Beaver Dam, WI  2021-11-08T00:00:00.000-05:00          1  
1  Kekoskee  Beaver Dam, WI  2022-03-14T00:00:00.000-04:00          1  
2  Kekoskee  Beaver Dam, WI  2021-11-08T00:00:00.000-05:00          1  
3  Kekoskee  Beaver Dam, WI  2022-03-14T00:00:00.000-04:00          1  
4  Kekoskee  Beaver Dam, WI  2021-11-08T00:00:00.000-05:00          1

In [9]:
df_p['Date Local'].str[0:10]

0          2015-01-01
1          2021-01-01
2          2015-01-02
3          2021-01-02
4          2015-01-03
              ...    
1241285    2016-12-27
1241286    2016-12-28
1241287    2016-12-29
1241288    2016-12-30
1241289    2016-12-31
Name: Date Local, Length: 1241290, dtype: object

In [10]:
df_p['Date Local standard'] = df_p['Date Local'].str[0:10]

In [11]:
df_p.head(5)

Latitude  Longitude  POC Event Type  count  State Code  County Code  \
0  43.46611  -88.62111    1       None   5072          55           27   
1  43.46611  -88.62111    1       None   5072          55           27   
2  43.46611  -88.62111    1       None   5072          55           27   
3  43.46611  -88.62111    1       None   5072          55           27   
4  43.46611  -88.62111    1       None   5072          55           27   

   Site Num  Parameter Code  Datum   Parameter Name Sample Duration  \
0         1           42101  WGS84  Carbon monoxide          1 HOUR   
1         1           42101  WGS84  Carbon monoxide          1 HOUR   
2         1           42101  WGS84  Carbon monoxide          1 HOUR   
3         1           42101  WGS84  Carbon monoxide          1 HOUR   
4         1           42101  WGS84  Carbon monoxide          1 HOUR   

  Pollutant Standard                     Date Local   Units of Measure  \
0     CO 1-hour 1971  2015-01-01T00:00:00.000-05:00  Parts per million   
1     CO 1-hour 1971  2021-01-01T00:00:00.000-05:00  Parts per million   
2     CO 1-hour 1971  2015-01-02T00:00:00.000-05:00  Parts per million   
3     CO 1-hour 1971  2021-01-02T00:00:00.000-05:00  Parts per million   
4     CO 1-hour 1971  2015-01-03T00:00:00.000-05:00  Parts per million   

   Observation Count  Observation Percent  Arithmetic Mean  1st Max Value  \
0                 23                 96.0         0.189739          0.213   
1                 23                 96.0         0.235087          0.262   
2                 23                 96.0         0.216130          0.343   
3                 23                 96.0         0.204130          0.232   
4                 23                 96.0         0.337783          0.377   

   1st Max Hour  AQI  Method Code  \
0             0  NaN        593.0   
1            18  NaN        593.0   
2            23  NaN        593.0   
3            21  NaN        593.0   
4             9  NaN        593.0   

                                         Method Name        Local Site Name  \
0  INSTRUMENTAL - Gas Filter Correlation Teledyne...  HORICON WILDLIFE AREA   
1  INSTRUMENTAL - Gas Filter Correlation Teledyne...  HORICON WILDLIFE AREA   
2  INSTRUMENTAL - Gas Filter Correlation Teledyne...  HORICON WILDLIFE AREA   
3  INSTRUMENTAL - Gas Filter Correlation Teledyne...  HORICON WILDLIFE AREA   
4  INSTRUMENTAL - Gas Filter Correlation Teledyne...  HORICON WILDLIFE AREA   

                                      Address State Name County Name  \
0  Horicon Wildlife Area, 1210 N Palmatory St  Wisconsin       Dodge   
1  Horicon Wildlife Area, 1210 N Palmatory St  Wisconsin       Dodge   
2  Horicon Wildlife Area, 1210 N Palmatory St  Wisconsin       Dodge   
3  Horicon Wildlife Area, 1210 N Palmatory St  Wisconsin       Dodge   
4  Horicon Wildlife Area, 1210 N Palmatory St  Wisconsin       Dodge   

  City Name       CBSA Name            Date of Last Change  point_num  \
0  Kekoskee  Beaver Dam, WI  2021-11-08T00:00:00.000-05:00          1   
1  Kekoskee  Beaver Dam, WI  2022-03-14T00:00:00.000-04:00          1   
2  Kekoskee  Beaver Dam, WI  2021-11-08T00:00:00.000-05:00          1   
3  Kekoskee  Beaver Dam, WI  2022-03-14T00:00:00.000-04:00          1   
4  Kekoskee  Beaver Dam, WI  2021-11-08T00:00:00.000-05:00          1   

  Date Local standard  
0          2015-01-01  
1          2021-01-01  
2          2015-01-02  
3          2021-01-02  
4          2015-01-03

In [19]:
df_p[(df_p['City Name'] == "Pittsburgh") & (df_p['Date Local standard'] == '2015-05-05')]

Latitude  Longitude  POC Event Type  count  State Code  County Code  \
515898  40.465420 -79.960757    2       None   4770          42            3   
516346  40.465420 -79.960757    2       None   4770          42            3   
819195  40.443367 -79.990293    1       None   4189          42            3   
819925  40.443367 -79.990293    1       None   4189          42            3   

        Site Num  Parameter Code  Datum   Parameter Name  \
515898         8           42101  WGS84  Carbon monoxide   
516346         8           42101  WGS84  Carbon monoxide   
819195        31           42101  WGS84  Carbon monoxide   
819925        31           42101  WGS84  Carbon monoxide   

              Sample Duration Pollutant Standard  \
515898                 1 HOUR     CO 1-hour 1971   
516346  8-HR RUN AVG END HOUR     CO 8-hour 1971   
819195                 1 HOUR     CO 1-hour 1971   
819925  8-HR RUN AVG END HOUR     CO 8-hour 1971   

                           Date Local   Units of Measure  Observation Count  \
515898  2015-05-05T00:00:00.000-04:00  Parts per million                 23   
516346  2015-05-05T00:00:00.000-04:00  Parts per million                 24   
819195  2015-05-05T00:00:00.000-04:00  Parts per million                 23   
819925  2015-05-05T00:00:00.000-04:00  Parts per million                 24   

        Observation Percent  Arithmetic Mean  1st Max Value  1st Max Hour  \
515898                 96.0         0.255739          0.372             7   
516346                100.0         0.237500          0.300             7   
819195                 96.0         0.352174          0.700            20   
819925                100.0         0.300000          0.500            23   

        AQI  Method Code                                        Method Name  \
515898  NaN        593.0  INSTRUMENTAL - Gas Filter Correlation Teledyne...   
516346  3.0          NaN                                                  -   
819195  NaN         93.0  INSTRUMENTAL - GAS FILTER CORRELATION CO ANALYZER   
819925  6.0          NaN                                                  -   

       Local Site Name                                            Address  \
515898   Lawrenceville  301 39th St, Pittsburgh, PA 15201 (Lawrenceville)   
516346   Lawrenceville  301 39th St, Pittsburgh, PA 15201 (Lawrenceville)   
819195      Flag Plaza  1275 Bedford Ave, Pittsburgh, PA 15219 (Flag P...   
819925      Flag Plaza  1275 Bedford Ave, Pittsburgh, PA 15219 (Flag P...   

          State Name County Name   City Name       CBSA Name  \
515898  Pennsylvania   Allegheny  Pittsburgh  Pittsburgh, PA   
516346  Pennsylvania   Allegheny  Pittsburgh  Pittsburgh, PA   
819195  Pennsylvania   Allegheny  Pittsburgh  Pittsburgh, PA   
819925  Pennsylvania   Allegheny  Pittsburgh  Pittsburgh, PA   

                  Date of Last Change  point_num Date Local standard  
515898  2021-11-08T00:00:00.000-05:00        117          2015-05-05  
516346  2021-11-08T00:00:00.000-05:00        117          2015-05-05  
819195  2021-11-08T00:00:00.000-05:00        183          2015-05-05  
819925  2021-11-08T00:00:00.000-05:00        183          2015-05-05

# CO Data


In [15]:
start_time="2015-01-01"

end_time="2021-12-31"

# days should be 2257

pdates = pd.date_range(start=start_time, end=end_time)

em = []

Coordinates = Coordinates_p.to_numpy()

Values = []

for i in range(1,num+1,1):
    
    #df_sub_p = df_p[df_p["point_num"] == i].set_index("Date Local")
    
    #df_sub_p_resampled = df_sub_p.resample("D").mean()
    
    #df_sub_p_365 = df_sub_p_resampled.fillna(df_sub_p_resampled.mean())
    
    #z = df_sub_p_365.iloc[:,9].to_numpy()# Daily Arithmetic Mean
    
    df_sub_p = df_p[df_p["point_num"] == i].set_index("Date Local standard")
    
    if (True in df_sub_p.index.duplicated()):
        print("df_sub_p duplicated index, point num is",i)
        em.append(i)
    else:

        df_sub_p_reindex = df_sub_p.reindex(pdates,fill_value=None)

        df_sub_p_365 = df_sub_p_reindex.fillna(df_sub_p_reindex.mean())

        #z = df_sub_p_365.iloc[:,17].to_numpy()# Daily Arithmetic Mean
        z = df_sub_p_365['Arithmetic Mean'].to_numpy()# Daily Arithmetic Mean

        if len(z)==2557:
            Values.append(z)
        else:
            print("Not 2557, point num is",i)
    
Values = np.array(Values)

df_sub_p duplicated index, point num is 1
df_sub_p duplicated index, point num is 2
df_sub_p duplicated index, point num is 3
df_sub_p duplicated index, point num is 4
df_sub_p duplicated index, point num is 5
df_sub_p duplicated index, point num is 6
df_sub_p duplicated index, point num is 7
df_sub_p duplicated index, point num is 8
df_sub_p duplicated index, point num is 9
df_sub_p duplicated index, point num is 10
df_sub_p duplicated index, point num is 11
df_sub_p duplicated index, point num is 12
df_sub_p duplicated index, point num is 13
df_sub_p duplicated index, point num is 14
df_sub_p duplicated index, point num is 15
df_sub_p duplicated index, point num is 16
df_sub_p duplicated index, point num is 17
df_sub_p duplicated index, point num is 18
df_sub_p duplicated index, point num is 19
df_sub_p duplicated index, point num is 20
df_sub_p duplicated index, point num is 21
df_sub_p duplicated index, point num is 22
df_sub_p duplicated index, point num is 23
df_sub_p duplicated 

In [16]:
df_sub_p

Latitude   Longitude  POC Event Type  count  State Code  \
Date Local standard                                                            
2019-01-01           37.97231 -122.520004    1       None   5089           6   
2017-01-01           37.97231 -122.520004    1       None   5089           6   
2019-01-02           37.97231 -122.520004    1       None   5089           6   
2017-01-02           37.97231 -122.520004    1       None   5089           6   
2019-01-03           37.97231 -122.520004    1       None   5089           6   
...                       ...         ...  ...        ...    ...         ...   
2016-12-27           37.97231 -122.520004    1       None   5089           6   
2016-12-28           37.97231 -122.520004    1       None   5089           6   
2016-12-29           37.97231 -122.520004    1       None   5089           6   
2016-12-30           37.97231 -122.520004    1       None   5089           6   
2016-12-31           37.97231 -122.520004    1       None   5089           6   

                     County Code  Site Num  Parameter Code  Datum  \
Date Local standard                                                 
2019-01-01                    41         1           42101  WGS84   
2017-01-01                    41         1           42101  WGS84   
2019-01-02                    41         1           42101  WGS84   
2017-01-02                    41         1           42101  WGS84   
2019-01-03                    41         1           42101  WGS84   
...                          ...       ...             ...    ...   
2016-12-27                    41         1           42101  WGS84   
2016-12-28                    41         1           42101  WGS84   
2016-12-29                    41         1           42101  WGS84   
2016-12-30                    41         1           42101  WGS84   
2016-12-31                    41         1           42101  WGS84   

                      Parameter Name        Sample Duration  \
Date Local standard                                           
2019-01-01           Carbon monoxide                 1 HOUR   
2017-01-01           Carbon monoxide                 1 HOUR   
2019-01-02           Carbon monoxide                 1 HOUR   
2017-01-02           Carbon monoxide                 1 HOUR   
2019-01-03           Carbon monoxide                 1 HOUR   
...                              ...                    ...   
2016-12-27           Carbon monoxide  8-HR RUN AVG END HOUR   
2016-12-28           Carbon monoxide  8-HR RUN AVG END HOUR   
2016-12-29           Carbon monoxide  8-HR RUN AVG END HOUR   
2016-12-30           Carbon monoxide  8-HR RUN AVG END HOUR   
2016-12-31           Carbon monoxide  8-HR RUN AVG END HOUR   

                    Pollutant Standard                     Date Local  \
Date Local standard                                                     
2019-01-01              CO 1-hour 1971  2019-01-01T00:00:00.000-05:00   
2017-01-01              CO 1-hour 1971  2017-01-01T00:00:00.000-05:00   
2019-01-02              CO 1-hour 1971  2019-01-02T00:00:00.000-05:00   
2017-01-02              CO 1-hour 1971  2017-01-02T00:00:00.000-05:00   
2019-01-03              CO 1-hour 1971  2019-01-03T00:00:00.000-05:00   
...                                ...                            ...   
2016-12-27              CO 8-hour 1971  2016-12-27T00:00:00.000-05:00   
2016-12-28              CO 8-hour 1971  2016-12-28T00:00:00.000-05:00   
2016-12-29              CO 8-hour 1971  2016-12-29T00:00:00.000-05:00   
2016-12-30              CO 8-hour 1971  2016-12-30T00:00:00.000-05:00   
2016-12-31              CO 8-hour 1971  2016-12-31T00:00:00.000-05:00   

                      Units of Measure  Observation Count  \
Date Local standard                                         
2019-01-01           Parts per million                 23   
2017-01-01           Parts per million                 23   
2019-01-02           Parts per million                 23   
2017-01

In [17]:
df_sub_p_reindex

NameError: name 'df_sub_p_reindex' is not defined

In [88]:
Coordinates.shape

(626, 2)

In [89]:
Values.shape

(626, 2557)

In [96]:
Values[3]

array([nan, nan, nan, ..., nan, nan, nan])

# Coordinate Data for Pitts 

[40.46542,-79.960757]


In [75]:
np.where(Coordinates==40.46542)

(array([575]), array([0]))

In [76]:
Coordinates[575]

array([ 40.46542 , -79.960757])

# X and Y for model

In [77]:
x=np.zeros((num-1,2557,3))
cord=np.delete(Coordinates,575,axis=0)-Coordinates[575]
valu=np.delete(Values,575,axis=0)

for m in range(num-1):
    for n in range(2557):
        x[m,n,0]=cord[m,0]
        x[m,n,1]=cord[m,1]
        x[m,n,2]=valu[m,0]

In [81]:
valu[1]

array([nan, nan, nan, ..., nan, nan, nan])

In [78]:
x.shape

(625, 2557, 3)

In [80]:
x[1,1,]

array([ -4.632694, -13.247503,        nan])

In [ ]:
y = Values.reshape()